### ISSUE TITLE
Gateway not launching on release mode

### ISSUE THREAD

**Issue by momoDragon** [MOLPay/molpay-mobile-xdk-flutter-beta#8]
When testing on emulator on debug mode it works.
When using appbundle in release mode and uploading it to google play for internal testing, the gateway launching screen shows but then it is dismissed and no gateway is shown.

**Note: I am using sandbox account.** 

Is there a way to test the gateway in release mode appbundle ?

**Comment by wasddsaw** [comment]
Hi @momoDragon , kindly provide us :-

- video record or screenshot.
- attach your pubspec.yaml file
- Please state your current XDK version. Example below -

<img width="407" alt="Screenshot 2020-06-11 at 3 05 46 PM" src="https://user-images.githubusercontent.com/23319632/84459106-31945580-ac99-11ea-927e-89cb91c77d8d.png">

**Comment by momoDragon** [comment]
**pubspec.yaml:**
https://pastebin.com/WcfwDf1e

**Debug Mode:**
https://drive.google.com/file/d/1RVg5yymOVDTFYMSS9P1KC4QKEB3ALF58/view?usp=sharing

**Release Mode:**
https://drive.google.com/file/d/1yhfRt9B-KFFuDSIGEO-_QDZPbL5UTqWT/view?usp=sharing

**XDK version:**
V3.29.0.0

**Comment by wasddsaw** [comment]
Hi @momoDragon , we cannot access your pubspec.yaml

**Comment by momoDragon** [comment]
```
name: my_fund_customer
description: A new Flutter application.
 
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
 
environment:
  sdk: ">=2.1.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter
 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.3
  flutter_bloc: ^4.0.0
  firebase_auth: ^0.16.0
  cloud_functions: ^0.4.2+3
  flutter_icons: ^1.1.0
  vibration: ^1.2.4
  flutter_money_formatter: ^0.8.3
  file_picker: ^1.9.0+1
  image_picker: ^0.6.6+1
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  cached_network_image: ^2.2.0+1
  google_fonts: ^1.1.0
  string_validator: ^0.1.4
  fluttertoast: ^4.0.1
  molpay_mobile_xdk_flutter_beta: ^0.29.1
 
 
dev_dependencies:
  flutter_test:
    sdk: flutter
 
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
 
 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
 
# The following section is specific to Flutter.
flutter:
 
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
 
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/logo/
    - assets/graphics/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
 
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
 
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comic Sans MS
      fonts:
        - asset: assets/fonts/Comic Sans MS 400.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
